repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        types_or: [yaml]
  - repo: local
    hooks:
      - id: format
        name: Format
        entry: script/format
        language: python
